In [34]:
import pandas as pd
import numpy as np

## Read and clean census data tables separately

### Data Table DP02

In [35]:
# By default 1st line in csv read as header of df
df = pd.read_csv('../data/raw/DP02.csv')   
print(df.shape)
df.head()

(171, 620)

,GEO_ID,NAME,POPGROUP,POPGROUP_LABEL,DP02_0001E,DP02_0001M,DP02_0002E,DP02_0002M,DP02_0003E,DP02_0003M,...,DP02_0150PE,DP02_0150PM,DP02_0151PE,DP02_0151PM,DP02_0152PE,DP02_0152PM,DP02_0153PE,DP02_0153PM,DP02_0154PE,DP02_0154PM
0,geo_id,census_tract,NaN,NaN,total_pop_household,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Geography,Geographic Area Name,Race/Ethnic Group,Population Groups,Estimate!!HOUSEHOLDS BY TYPE!!Total households,Margin of Error!!HOUSEHOLDS BY TYPE!!Total hou...,Estimate!!HOUSEHOLDS BY TYPE!!Total households...,Margin of Error!!HOUSEHOLDS BY TYPE!!Total hou...,Estimate!!HOUSEHOLDS BY TYPE!!Total households...,Margin of Error!!HOUSEHOLDS BY TYPE!!Total hou...,...,Percent!!ANCESTRY!!Total population!!Welsh,Percent Margin of Error!!ANCESTRY!!Total popul...,Percent!!ANCESTRY!!Total population!!West Indi...,Percent Margin of Error!!ANCESTRY!!Total popul...,Percent!!COMPUTERS AND INTERNET USE!!Total hou...,Percent Margin of Error!!COMPUTERS AND INTERNE...,Percent!!COMPUTERS AND INTERNET USE!!Total hou...,Percent Margin of Error!!COMPUTERS AND INTERNE...,Percent!!COMPUTERS AND INTERNET USE!!Total hou...,Percent Margin of Error!!COMPUTERS AND INTERNE...
2,1400000US16055000101,Census Tract 1.01; Kootenai County; Idaho,1,Total population,1126,202,1006,200,243,111,...,(X),(X),(X),(X),1126,(X),98.4,2.4,78.9,10.4
3,1400000US16055000102,Census Tract 1.02; Kootenai County; Idaho,1,Total population,1604,169,1211,166,221,49,...,(X),(X),(X),(X),1604,(X),95.5,2.6,87.7,5.6
4,1400000US16055000201,Census Tract 2.01; Kootenai County; Idaho,1,Total population,1158,204,893,203,453,179,...,(X),(X),(X),(X),1158,(X),100,3.2,95.9,4.5

### In the csv file the 1st line is the variable names, 2nd line is selected variables with new names, 3nd line is metadata.

In [36]:
# Keep columns where first row (iloc[0]) is not null
df = df.loc[:, df.iloc[0].notnull()]
print("Number of columns:", df.shape[1])
df.head()

Number of columns: 19

,GEO_ID,NAME,DP02_0001E,DP02_0059PE,DP02_0062PE,DP02_0063PE,DP02_0064PE,DP02_0065PE,DP02_0066PE,DP02_0080PE,DP02_0081PE,DP02_0082PE,DP02_0083PE,DP02_0084PE,DP02_0085PE,DP02_0086PE,DP02_0087PE,DP02_0089PE,DP02_0094PE
0,geo_id,census_tract,total_pop_household,pop25,pct_high_school,pct_some_college,pct_associate,pct_bachelor,pct_graduate,pct_same_house,pct_diff_house,pct_diff_house_us,pct_same_county,pct_diff_county,pct_diffCounty_sState,pct_diff_state,pct_abroad,pct_native,pct_foreign_born
1,Geography,Geographic Area Name,Estimate!!HOUSEHOLDS BY TYPE!!Total households,Percent!!EDUCATIONAL ATTAINMENT!!Population 25...,Percent!!EDUCATIONAL ATTAINMENT!!Population 25...,Percent!!EDUCATIONAL ATTAINMENT!!Population 25...,Percent!!EDUCATIONAL ATTAINMENT!!Population 25...,Percent!!EDUCATIONAL ATTAINMENT!!Population 25...,Percent!!EDUCATIONAL ATTAINMENT!!Population 25...,Percent!!RESIDENCE 1 YEAR AGO!!Population 1 ye...,Percent!!RESIDENCE 1 YEAR AGO!!Population 1 ye...,Percent!!RESIDENCE 1 YEAR AGO!!Population 1 ye...,Percent!!RESIDENCE 1 YEAR AGO!!Population 1 ye...,Percent!!RESIDENCE 1 YEAR AGO!!Population 1 ye...,Percent!!RESIDENCE 1 YEAR AGO!!Population 1 ye...,Percent!!RESIDENCE 1 YEAR AGO!!Population 1 ye...,Percent!!RESIDENCE 1 YEAR AGO!!Population 1 ye...,Percent!!PLACE OF BIRTH!!Total population!!Native,Percent!!PLACE OF BIRTH!!Total population!!For...
2,1400000US16055000101,Census Tract 1.01; Kootenai County; Idaho,1126,2324,26.7,22.4,16.6,21.6,9.3,89.7,10.3,10.3,1.5,8.8,0.2,8.6,0,100,0
3,1400000US16055000102,Census Tract 1.02; Kootenai County; Idaho,1604,3341,32.1,32.1,13.2,12.7,6,88.5,11.5,11.5,2.8,8.7,0.6,8.1,0,99.5,0.5
4,1400000US16055000201,Census Tract 2.01; Kootenai County; Idaho,1158,2381,27.2,31.9,8.4,19.3,9.3,84.4,15.6,14.7,10.1,4.6,0.7,3.9,0.9,98.4,1.6

In [37]:
# Use 1st row as column names
df.columns = df.iloc[0]
# Remove first two rows (header + metadata)
df = df.iloc[2:]
# Reset index
df = df.reset_index(drop=True)
df.head()

,geo_id,census_tract,total_pop_household,pop25,pct_high_school,pct_some_college,pct_associate,pct_bachelor,pct_graduate,pct_same_house,pct_diff_house,pct_diff_house_us,pct_same_county,pct_diff_county,pct_diffCounty_sState,pct_diff_state,pct_abroad,pct_native,pct_foreign_born
0,1400000US16055000101,Census Tract 1.01; Kootenai County; Idaho,1126,2324,26.7,22.4,16.6,21.6,9.3,89.7,10.3,10.3,1.5,8.8,0.2,8.6,0,100,0
1,1400000US16055000102,Census Tract 1.02; Kootenai County; Idaho,1604,3341,32.1,32.1,13.2,12.7,6,88.5,11.5,11.5,2.8,8.7,0.6,8.1,0,99.5,0.5
2,1400000US16055000201,Census Tract 2.01; Kootenai County; Idaho,1158,2381,27.2,31.9,8.4,19.3,9.3,84.4,15.6,14.7,10.1,4.6,0.7,3.9,0.9,98.4,1.6
3,1400000US16055000202,Census Tract 2.02; Kootenai County; Idaho,1276,2571,23.7,21.7,17.7,18,13.9,91.5,8.5,8.5,7.6,0.9,0.1,0.8,0,97.3,2.7
4,1400000US16055000203,Census Tract 2.03; Kootenai County; Idaho,1300,2368,39.1,21.9,6.3,20.4,3.4,95,5,5,1.9,3.1,0,3.1,0,98.4,1.6

In [38]:
# Select columns 
print("Columns before:", df.columns)
df = df.drop(['total_pop_household', 'pop25'], axis=1)
print("Columns after:", df.columns)
print(df.info())

Columns before: Index(['geo_id', 'census_tract', 'total_pop_household', 'pop25',
       'pct_high_school', 'pct_some_college', 'pct_associate', 'pct_bachelor',
       'pct_graduate', 'pct_same_house', 'pct_diff_house', 'pct_diff_house_us',
       'pct_same_county', 'pct_diff_county', 'pct_diffCounty_sState',
       'pct_diff_state', 'pct_abroad', 'pct_native', 'pct_foreign_born'],
      dtype='object', name=0)
Columns after: Index(['geo_id', 'census_tract', 'pct_high_school', 'pct_some_college',
       'pct_associate', 'pct_bachelor', 'pct_graduate', 'pct_same_house',
       'pct_diff_house', 'pct_diff_house_us', 'pct_same_county',
       'pct_diff_county', 'pct_diffCounty_sState', 'pct_diff_state',
       'pct_abroad', 'pct_native', 'pct_foreign_born'],
      dtype='object', name=0)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   geo_id                 169 non-null    object
 1   census_tract           169 non-null    object
 2   pct_high_school        169 non-null    object
 3   pct_some_college       169 non-null    object
 4   pct_associate          169 non-null    object
 5   pct_bachelor           169 non-null    object
 6   pct_graduate           169 non-null    object
 7   pct_same_house         169 non-null    object
 8   pct_diff_house         169 non-null    object
 9   pct_diff_house_us      169 non-null    object
 10  pct_same_county        169 non-null    object
 11  pct_diff_county        169 non-null    object
 12  pct_diffCounty_sState  169 non-null    object
 13  pct_diff_state         169 non-null    object
 14  pct_abroad             169 non-null    object
 15  pct_native             169 non-null    object
 16  pct_foreign_born       169 non-null    object
dtypes: object(17)
memory usage: 22.6+ KB
None

In [39]:
# Convert data types
numeric_column_list = ['pct_high_school', 'pct_some_college',
       'pct_associate', 'pct_bachelor', 'pct_graduate', 'pct_same_house',
       'pct_diff_house', 'pct_diff_house_us', 'pct_same_county',
       'pct_diff_county', 'pct_diffCounty_sState', 'pct_diff_state',
       'pct_abroad', 'pct_native', 'pct_foreign_born']
for numeric_column in numeric_column_list:
    df[numeric_column] = df[numeric_column].astype(float)
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   geo_id                 169 non-null    object
 1   census_tract           169 non-null    object
 2   pct_high_school        169 non-null    float64
 3   pct_some_college       169 non-null    float64
 4   pct_associate          169 non-null    float64
 5   pct_bachelor           169 non-null    float64
 6   pct_graduate           169 non-null    float64
 7   pct_same_house         169 non-null    float64
 8   pct_diff_house         169 non-null    float64
 9   pct_diff_house_us      169 non-null    float64
 10  pct_same_county        169 non-null    float64
 11  pct_diff_county        169 non-null    float64
 12  pct_diffCounty_sState  169 non-null    float64
 13  pct_diff_state         169 non-null    float64
 14  pct_abroad             169 non-null    float64
 15  pct_native             169 non-null    float64
 16  pct_foreign_born       169 non-null    float64
dtypes: float64(15), object(2)
memory usage: 22.6+ KB
None

In [40]:
# Check missing values
print(df.isnull().sum())

# Save the cleaned dataset
df.to_csv('../data/processed/DP02_clean.csv', index=False)

0
geo_id                   0
census_tract             0
pct_high_school          0
pct_some_college         0
pct_associate            0
pct_bachelor             0
pct_graduate             0
pct_same_house           0
pct_diff_house           0
pct_diff_house_us        0
pct_same_county          0
pct_diff_county          0
pct_diffCounty_sState    0
pct_diff_state           0
pct_abroad               0
pct_native               0
pct_foreign_born         0
dtype: int64

### Data Table DP03

In [41]:
df = pd.read_csv('../data/raw/DP03.csv')   
print(df.shape)
# Keep columns where first row (iloc[0]) is not null
df = df.loc[:, df.iloc[0].notnull()]
print("Number of columns:", df.shape[1])
# Use 1st row as column names
df.columns = df.iloc[0]
# Remove first two rows (names + metadata)
df = df.iloc[2:]
# Reset index
df = df.reset_index(drop=True)
df.head()

(171, 552)
Number of columns: 5

,geo_id,census_tract,pop16,unemploy_rate,pct_below_poverty
0,1400000US16055000101,Census Tract 1.01; Kootenai County; Idaho,2535,1.9,6.3
1,1400000US16055000102,Census Tract 1.02; Kootenai County; Idaho,3687,3.8,3.7
2,1400000US16055000201,Census Tract 2.01; Kootenai County; Idaho,2863,2.5,7.4
3,1400000US16055000202,Census Tract 2.02; Kootenai County; Idaho,2841,3.7,6.7
4,1400000US16055000203,Census Tract 2.03; Kootenai County; Idaho,2818,1.2,14

In [42]:
# Select columns 
print("Columns before:", df.columns)
df = df.drop(['pop16'], axis=1)
print("Columns after:", df.columns)
print(df.head())
print(df.info())

Columns before: Index(['geo_id', 'census_tract', 'pop16', 'unemploy_rate',
       'pct_below_poverty'],
      dtype='object', name=0)
Columns after: Index(['geo_id', 'census_tract', 'unemploy_rate', 'pct_below_poverty'], dtype='object', name=0)
0                geo_id                               census_tract  \
0  1400000US16055000101  Census Tract 1.01; Kootenai County; Idaho
1  1400000US16055000102  Census Tract 1.02; Kootenai County; Idaho
2  1400000US16055000201  Census Tract 2.01; Kootenai County; Idaho
3  1400000US16055000202  Census Tract 2.02; Kootenai County; Idaho
4  1400000US16055000203  Census Tract 2.03; Kootenai County; Idaho

0 unemploy_rate pct_below_poverty
0           1.9               6.3
1           3.8               3.7
2           2.5               7.4
3           3.7               6.7
4           1.2                14
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   geo_id             169 non-null    object
 1   census_tract       169 non-null    object
 2   unemploy_rate      169 non-null    object
 3   pct_below_poverty  169 non-null    object
dtypes: object(4)
memory usage: 5.4+ KB
None

In [43]:
# Convert data types
numeric_column_list = ['unemploy_rate', 'pct_below_poverty']
for numeric_column in numeric_column_list:
    df[numeric_column] = df[numeric_column].astype(float)
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   geo_id             169 non-null    object
 1   census_tract       169 non-null    object
 2   unemploy_rate      169 non-null    float64
 3   pct_below_poverty  169 non-null    float64
dtypes: float64(2), object(2)
memory usage: 5.4+ KB
None

In [44]:
# Check missing values
print(df.isnull().sum())

# Save the cleaned dataset
df.to_csv('../data/processed/DP03_clean.csv', index=False)

0
geo_id               0
census_tract         0
unemploy_rate        0
pct_below_poverty    0
dtype: int64

### Data Table DP04

In [45]:
df = pd.read_csv('../data/raw/DP04.csv')   
print(df.shape)
# Keep columns where first row (iloc[0]) is not null
df = df.loc[:, df.iloc[0].notnull()]
print("Number of columns:", df.shape[1])
# Use 1st row as column names
df.columns = df.iloc[0]
# Remove first two rows (names + metadata)
df = df.iloc[2:]
# Reset index
df = df.reset_index(drop=True)
df.head()

(171, 576)
Number of columns: 12

,geo_id,census_tract,count_house_owner,median_house_value,count_house_rent,gross_rent_median,count_occupied_house,pct_owner_occupied,pct_renter_occupied,pct_houseValue300k,pct_houseValue500k,pct_houseValue1M
0,1400000US16055000101,Census Tract 1.01; Kootenai County; Idaho,1057,294500,69,-,1126,93.9,6.1,24.6,23.7,0
1,1400000US16055000102,Census Tract 1.02; Kootenai County; Idaho,1407,335700,178,971,1604,87.7,12.3,43.5,12.7,2.1
2,1400000US16055000201,Census Tract 2.01; Kootenai County; Idaho,1098,387800,47,1607,1158,94.8,5.2,42.3,25.4,0
3,1400000US16055000202,Census Tract 2.02; Kootenai County; Idaho,1187,414700,73,-,1276,93,7,52,27.5,2.2
4,1400000US16055000203,Census Tract 2.03; Kootenai County; Idaho,1022,320400,278,984,1300,78.6,21.4,30,22.9,0

In [46]:
# Select columns 
print("Columns before:", df.columns)
df = df.drop(['count_house_rent', 'count_house_owner', 
    'count_occupied_house', 'pct_owner_occupied',], axis=1)
print("Columns after:", df.columns)
print(df.dtypes)

Columns before: Index(['geo_id', 'census_tract', 'count_house_owner', 'median_house_value',
       'count_house_rent', 'gross_rent_median', 'count_occupied_house',
       'pct_owner_occupied', 'pct_renter_occupied', 'pct_houseValue300k',
       'pct_houseValue500k', 'pct_houseValue1M'],
      dtype='object', name=0)
Columns after: Index(['geo_id', 'census_tract', 'median_house_value', 'gross_rent_median',
       'pct_renter_occupied', 'pct_houseValue300k', 'pct_houseValue500k',
       'pct_houseValue1M'],
      dtype='object', name=0)
0
geo_id                 object
census_tract           object
median_house_value     object
gross_rent_median      object
pct_renter_occupied    object
pct_houseValue300k     object
pct_houseValue500k     object
pct_houseValue1M       object
dtype: object

In [47]:
# Check missing values
print(df.isnull().sum())

# Convert data types
df['pct_renter_occupied'] = df['pct_renter_occupied'].astype(float)

# Replace any non-numeric values with NaN
df = df.replace({'-': np.nan, 'None': np.nan, '': np.nan})
selected_columns = ['median_house_value', 'pct_houseValue300k', 'pct_houseValue500k', 'pct_houseValue1M', 'gross_rent_median']
df[selected_columns] = df[selected_columns].apply(pd.to_numeric, errors='coerce')
print(df.dtypes)

0
geo_id                 0
census_tract           0
median_house_value     0
gross_rent_median      0
pct_renter_occupied    0
pct_houseValue300k     0
pct_houseValue500k     0
pct_houseValue1M       0
dtype: int64
0
geo_id                  object
census_tract            object
median_house_value     float64
gross_rent_median      float64
pct_renter_occupied    float64
pct_houseValue300k     float64
pct_houseValue500k     float64
pct_houseValue1M       float64
dtype: object

In [48]:
# Save the cleaned dataset
df.to_csv('../data/processed/DP04_clean.csv', index=False)

### Data Table DP05

In [49]:
df = pd.read_csv('../data/raw/DP05.csv')   
print(df.shape)
# Keep columns where first row (iloc[0]) is not null
df = df.loc[:, df.iloc[0].notnull()]
print("Number of columns:", df.shape[1])
# Use 1st row as column names
df.columns = df.iloc[0]
# Remove first two rows (names + metadata)
df = df.iloc[2:]
# Reset index
df = df.reset_index(drop=True)
df.head()

(171, 360)
Number of columns: 16

,geo_id,census_tract,pop_male,pop_female,median_age,pop_65years,pct_male,pct_female,pct_age2024,pct_age2534,pct_age3544,pct_age4554,pct_age5559,pct_age6064,pct_under18,pct_over65
0,1400000US16055000101,Census Tract 1.01; Kootenai County; Idaho,1562,1424,54,198,52.3,47.7,2.4,2.8,7.2,21.1,12.9,9.3,16.4,24.5
1,1400000US16055000102,Census Tract 1.02; Kootenai County; Idaho,2261,2280,47.3,213,49.8,50.2,5,8.5,12.5,12.2,9.8,12.1,20.1,18.4
2,1400000US16055000201,Census Tract 2.01; Kootenai County; Idaho,1653,1873,37.2,211,46.9,53.1,7.7,14.5,11.6,14.2,6.3,4.3,23.2,16.7
3,1400000US16055000202,Census Tract 2.02; Kootenai County; Idaho,1670,1684,54.3,259,49.8,50.2,2.3,4.9,8.3,17.8,11.8,12.9,18.9,21
4,1400000US16055000203,Census Tract 2.03; Kootenai County; Idaho,1655,1616,50.4,166,50.6,49.4,7.4,8.5,7.5,14.8,9.4,11.2,17.5,20.9

In [50]:
# Select columns 
print("Columns before:", df.columns)
df = df.drop(['pop_male', 'pop_female', 'pop_65years', 'pct_female'], axis=1)
print("Columns after:", df.columns)
print(df.dtypes) 
print(df.head())

Columns before: Index(['geo_id', 'census_tract', 'pop_male', 'pop_female', 'median_age',
       'pop_65years', 'pct_male', 'pct_female', 'pct_age2024', 'pct_age2534',
       'pct_age3544', 'pct_age4554', 'pct_age5559', 'pct_age6064',
       'pct_under18', 'pct_over65'],
      dtype='object', name=0)
Columns after: Index(['geo_id', 'census_tract', 'median_age', 'pct_male', 'pct_age2024',
       'pct_age2534', 'pct_age3544', 'pct_age4554', 'pct_age5559',
       'pct_age6064', 'pct_under18', 'pct_over65'],
      dtype='object', name=0)
0
geo_id          object
census_tract    object
median_age      object
pct_male        object
pct_age2024     object
pct_age2534     object
pct_age3544     object
pct_age4554     object
pct_age5559     object
pct_age6064     object
pct_under18     object
pct_over65      object
dtype: object
0                geo_id                               census_tract median_age  \
0  1400000US16055000101  Census Tract 1.01; Kootenai County; Idaho         54
1  1400000US16055000102  Census Tract 1.02; Kootenai County; Idaho       47.3
2  1400000US16055000201  Census Tract 2.01; Kootenai County; Idaho       37.2
3  1400000US16055000202  Census Tract 2.02; Kootenai County; Idaho       54.3
4  1400000US16055000203  Census Tract 2.03; Kootenai County; Idaho       50.4

0 pct_male pct_age2024 pct_age2534 pct_age3544 pct_age4554 pct_age5559  \
0     52.3         2.4         2.8         7.2        21.1        12.9
1     49.8           5         8.5        12.5        12.2         9.8
2     46.9         7.7        14.5        11.6        14.2         6.3
3     49.8         2.3         4.9         8.3        17.8        11.8
4     50.6         7.4         8.5         7.5        14.8         9.4

0 pct_age6064 pct_under18 pct_over65
0         9.3        16.4       24.5
1        12.1        20.1       18.4
2         4.3        23.2       16.7
3        12.9        18.9         21
4        11.2        17.5       20.9

In [51]:
# Check missing values
print(df.isnull().sum())

# Convert data types
num_col_list = ['median_age', 'pct_male', 'pct_under18', 'pct_age2024',
       'pct_age2534', 'pct_age3544', 'pct_age4554', 'pct_age5559',
       'pct_age6064', 'pct_under18', 'pct_over65']
for num_col in num_col_list:
    df[num_col] = df[num_col].astype(float)

print(df.dtypes)

0
geo_id          0
census_tract    0
median_age      0
pct_male        0
pct_age2024     0
pct_age2534     0
pct_age3544     0
pct_age4554     0
pct_age5559     0
pct_age6064     0
pct_under18     0
pct_over65      0
dtype: int64
0
geo_id           object
census_tract     object
median_age      float64
pct_male        float64
pct_age2024     float64
pct_age2534     float64
pct_age3544     float64
pct_age4554     float64
pct_age5559     float64
pct_age6064     float64
pct_under18     float64
pct_over65      float64
dtype: object

In [52]:
# Save the cleaned dataset
df.to_csv('../data/processed/DP05_clean.csv', index=False)